### ISSUE TITLE
Can't start gridstudy-app

### ISSUE THREAD

**Issue by cesar-luis-galli** [gridsuite/gridstudy-app#436]
I've downloaded to a local directory source code of gridstudy-app, then I've run `nmp install` and  `nmp start`.
Server starts in localhost:3000 as expected, but clicking Login button has no effect at all.
Here is the log stack (console):

```
ℹ ｢wds｣: Project is running at http://192.168.10.62/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from <local dir>/gridsuite/gridstudy-app-main/public
ℹ ｢wds｣: 404s will fallback to /
```

Besides. the following messages appears in the browser's debugging console:

`[Exception... "Favicon at "http://localhost:3000/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no] FaviconLoader.jsm:253:22`

What's the issue here? Is there a configuration parameter that I should set-up before executing nmp start?

**Comment by geofjamg** [comment]
Hi @cesar-luis-galli,
Have you tried the back-end installation guide https://github.com/gridsuite/deployment ?

**Comment by cesar-luis-galli** [comment]
> Hi @cesar-luis-galli, Have you tried the back-end installation guide https://github.com/gridsuite/deployment ?

Hi @geofjamg, thanks for your quick reply.
I've read it, but understood that the container installation was only required for development/integration.
So, I must install Cassandra, PostgreSQL, etc., and deploy a container for gridsuite?

**Comment by geofjamg** [comment]
If you just want to test the application, there is an online demo at https://demo.gridsuite.org with some studies already created from public data (like MicroGrids). You can connect to it with any microsoft related account (like github).
I you want to develop, you have to run both back-end and front-end on your computer and you also need indeed to start a cassandra and postgressql. It might be possible to run only the front-end in dev mode (so like you did using npm on gridexplore and gridstudy) using the cloud back-end so that you don't have to take care of back-end install. But this is not straightforward and I have to write how to in the doc. Let me known if you are interested.

**Comment by cesar-luis-galli** [comment]
I want to create my own cases on a local repository, so I'll install both (back an front end), following the deployment instructions.  
I've been using the on-line demo for the past few days. In fact, that's the reason why I want to try with my own grid.
Thanks by the offer and, again, your quick reply.
Everything is clear now, so I'll close the issue (that wasn't an issue).

Best regards,
César Galli.
